/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConviteCodeRouteImport } from './routes/convite.$code'
import { Route as AuthenticatedToolsRouteImport } from './routes/_authenticated.tools'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedRegistrarProducaoV3RouteImport } from './routes/_authenticated.registrar-producao-v3'
import { Route as AuthenticatedRegistrarProducaoV2RouteImport } from './routes/_authenticated.registrar-producao-v2'
import { Route as AuthenticatedRegistrarProducaoRouteImport } from './routes/_authenticated.registrar-producao'
import { Route as AuthenticatedRankingV3RouteImport } from './routes/_authenticated.ranking-v3'
import { Route as AuthenticatedRankingV2RouteImport } from './routes/_authenticated.ranking-v2'
import { Route as AuthenticatedRankingRouteImport } from './routes/_authenticated.ranking'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated.perfil'
import { Route as AuthenticatedMetasRouteImport } from './routes/_authenticated.metas'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/_authenticated.historico'
import { Route as AuthenticatedDesignSystemRouteImport } from './routes/_authenticated.design-system'
import { Route as AuthenticatedDashboardV3RouteImport } from './routes/_authenticated.dashboard-v3'
import { Route as AuthenticatedDashboardV2RouteImport } from './routes/_authenticated.dashboard-v2'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedContactsV3RouteImport } from './routes/_authenticated.contacts-v3'
import { Route as AuthenticatedContactsRouteImport } from './routes/_authenticated.contacts'
import { Route as AuthenticatedCampanhasRouteImport } from './routes/_authenticated.campanhas'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedAdminProdutosRouteImport } from './routes/_authenticated.admin_.produtos'
import { Route as AuthenticatedAdminConvitesRouteImport } from './routes/_authenticated.admin_.convites'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConviteCodeRoute = ConviteCodeRouteImport.update({
  id: '/convite/$code',
  path: '/convite/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedToolsRoute = AuthenticatedToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRegistrarProducaoV3Route =
  AuthenticatedRegistrarProducaoV3RouteImport.update({
    id: '/registrar-producao-v3',
    path: '/registrar-producao-v3',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRegistrarProducaoV2Route =
  AuthenticatedRegistrarProducaoV2RouteImport.update({
    id: '/registrar-producao-v2',
    path: '/registrar-producao-v2',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRegistrarProducaoRoute =
  AuthenticatedRegistrarProducaoRouteImport.update({
    id: '/registrar-producao',
    path: '/registrar-producao',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRankingV3Route = AuthenticatedRankingV3RouteImport.update({
  id: '/ranking-v3',
  path: '/ranking-v3',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRankingV2Route = AuthenticatedRankingV2RouteImport.update({
  id: '/ranking-v2',
  path: '/ranking-v2',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRankingRoute = AuthenticatedRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMetasRoute = AuthenticatedMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDesignSystemRoute =
  AuthenticatedDesignSystemRouteImport.update({
    id: '/design-system',
    path: '/design-system',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardV3Route =
  AuthenticatedDashboardV3RouteImport.update({
    id: '/dashboard-v3',
    path: '/dashboard-v3',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardV2Route =
  AuthenticatedDashboardV2RouteImport.update({
    id: '/dashboard-v2',
    path: '/dashboard-v2',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContactsV3Route = AuthenticatedContactsV3RouteImport.update({
  id: '/contacts-v3',
  path: '/contacts-v3',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContactsRoute = AuthenticatedContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCampanhasRoute = AuthenticatedCampanhasRouteImport.update({
  id: '/campanhas',
  path: '/campanhas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminProdutosRoute =
  AuthenticatedAdminProdutosRouteImport.update({
    id: '/admin_/produtos',
    path: '/admin/produtos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminConvitesRoute =
  AuthenticatedAdminConvitesRouteImport.update({
    id: '/admin_/convites',
    path: '/admin/convites',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/campanhas': typeof AuthenticatedCampanhasRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/contacts-v3': typeof AuthenticatedContactsV3Route
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dashboard-v2': typeof AuthenticatedDashboardV2Route
  '/dashboard-v3': typeof AuthenticatedDashboardV3Route
  '/design-system': typeof AuthenticatedDesignSystemRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/ranking': typeof AuthenticatedRankingRoute
  '/ranking-v2': typeof AuthenticatedRankingV2Route
  '/ranking-v3': typeof AuthenticatedRankingV3Route
  '/registrar-producao': typeof AuthenticatedRegistrarProducaoRoute
  '/registrar-producao-v2': typeof AuthenticatedRegistrarProducaoV2Route
  '/registrar-producao-v3': typeof AuthenticatedRegistrarProducaoV3Route
  '/settings': typeof AuthenticatedSettingsRoute
  '/tools': typeof AuthenticatedToolsRoute
  '/convite/$code': typeof ConviteCodeRoute
  '/admin/convites': typeof AuthenticatedAdminConvitesRoute
  '/admin/produtos': typeof AuthenticatedAdminProdutosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/campanhas': typeof AuthenticatedCampanhasRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/contacts-v3': typeof AuthenticatedContactsV3Route
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dashboard-v2': typeof AuthenticatedDashboardV2Route
  '/dashboard-v3': typeof AuthenticatedDashboardV3Route
  '/design-system': typeof AuthenticatedDesignSystemRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/ranking': typeof AuthenticatedRankingRoute
  '/ranking-v2': typeof AuthenticatedRankingV2Route
  '/ranking-v3': typeof AuthenticatedRankingV3Route
  '/registrar-producao': typeof AuthenticatedRegistrarProducaoRoute
  '/registrar-producao-v2': typeof AuthenticatedRegistrarProducaoV2Route
  '/registrar-producao-v3': typeof AuthenticatedRegistrarProducaoV3Route
  '/settings': typeof AuthenticatedSettingsRoute
  '/tools': typeof AuthenticatedToolsRoute
  '/convite/$code': typeof ConviteCodeRoute
  '/admin/convites': typeof AuthenticatedAdminConvitesRoute
  '/admin/produtos': typeof AuthenticatedAdminProdutosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/campanhas': typeof AuthenticatedCampanhasRoute
  '/_authenticated/contacts': typeof AuthenticatedContactsRoute
  '/_authenticated/contacts-v3': typeof AuthenticatedContactsV3Route
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/dashboard-v2': typeof AuthenticatedDashboardV2Route
  '/_authenticated/dashboard-v3': typeof AuthenticatedDashboardV3Route
  '/_authenticated/design-system': typeof AuthenticatedDesignSystemRoute
  '/_authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/_authenticated/metas': typeof AuthenticatedMetasRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/ranking': typeof AuthenticatedRankingRoute
  '/_authenticated/ranking-v2': typeof AuthenticatedRankingV2Route
  '/_authenticated/ranking-v3': typeof AuthenticatedRankingV3Route
  '/_authenticated/registrar-producao': typeof AuthenticatedRegistrarProducaoRoute
  '/_authenticated/registrar-producao-v2': typeof AuthenticatedRegistrarProducaoV2Route
  '/_authenticated/registrar-producao-v3': typeof AuthenticatedRegistrarProducaoV3Route
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tools': typeof AuthenticatedToolsRoute
  '/convite/$code': typeof ConviteCodeRoute
  '/_authenticated/admin_/convites': typeof AuthenticatedAdminConvitesRoute
  '/_authenticated/admin_/produtos': typeof AuthenticatedAdminProdutosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/admin'
    | '/campanhas'
    | '/contacts'
    | '/contacts-v3'
    | '/dashboard'
    | '/dashboard-v2'
    | '/dashboard-v3'
    | '/design-system'
    | '/historico'
    | '/metas'
    | '/perfil'
    | '/ranking'
    | '/ranking-v2'
    | '/ranking-v3'
    | '/registrar-producao'
    | '/registrar-producao-v2'
    | '/registrar-producao-v3'
    | '/settings'
    | '/tools'
    | '/convite/$code'
    | '/admin/convites'
    | '/admin/produtos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/admin'
    | '/campanhas'
    | '/contacts'
    | '/contacts-v3'
    | '/dashboard'
    | '/dashboard-v2'
    | '/dashboard-v3'
    | '/design-system'
    | '/historico'
    | '/metas'
    | '/perfil'
    | '/ranking'
    | '/ranking-v2'
    | '/ranking-v3'
    | '/registrar-producao'
    | '/registrar-producao-v2'
    | '/registrar-producao-v3'
    | '/settings'
    | '/tools'
    | '/convite/$code'
    | '/admin/convites'
    | '/admin/produtos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/campanhas'
    | '/_authenticated/contacts'
    | '/_authenticated/contacts-v3'
    | '/_authenticated/dashboard'
    | '/_authenticated/dashboard-v2'
    | '/_authenticated/dashboard-v3'
    | '/_authenticated/design-system'
    | '/_authenticated/historico'
    | '/_authenticated/metas'
    | '/_authenticated/perfil'
    | '/_authenticated/ranking'
    | '/_authenticated/ranking-v2'
    | '/_authenticated/ranking-v3'
    | '/_authenticated/registrar-producao'
    | '/_authenticated/registrar-producao-v2'
    | '/_authenticated/registrar-producao-v3'
    | '/_authenticated/settings'
    | '/_authenticated/tools'
    | '/convite/$code'
    | '/_authenticated/admin_/convites'
    | '/_authenticated/admin_/produtos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ConviteCodeRoute: typeof ConviteCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convite/$code': {
      id: '/convite/$code'
      path: '/convite/$code'
      fullPath: '/convite/$code'
      preLoaderRoute: typeof ConviteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tools': {
      id: '/_authenticated/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof AuthenticatedToolsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/registrar-producao-v3': {
      id: '/_authenticated/registrar-producao-v3'
      path: '/registrar-producao-v3'
      fullPath: '/registrar-producao-v3'
      preLoaderRoute: typeof AuthenticatedRegistrarProducaoV3RouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/registrar-producao-v2': {
      id: '/_authenticated/registrar-producao-v2'
      path: '/registrar-producao-v2'
      fullPath: '/registrar-producao-v2'
      preLoaderRoute: typeof AuthenticatedRegistrarProducaoV2RouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/registrar-producao': {
      id: '/_authenticated/registrar-producao'
      path: '/registrar-producao'
      fullPath: '/registrar-producao'
      preLoaderRoute: typeof AuthenticatedRegistrarProducaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ranking-v3': {
      id: '/_authenticated/ranking-v3'
      path: '/ranking-v3'
      fullPath: '/ranking-v3'
      preLoaderRoute: typeof AuthenticatedRankingV3RouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ranking-v2': {
      id: '/_authenticated/ranking-v2'
      path: '/ranking-v2'
      fullPath: '/ranking-v2'
      preLoaderRoute: typeof AuthenticatedRankingV2RouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ranking': {
      id: '/_authenticated/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof AuthenticatedRankingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/metas': {
      id: '/_authenticated/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof AuthenticatedMetasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/design-system': {
      id: '/_authenticated/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof AuthenticatedDesignSystemRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard-v3': {
      id: '/_authenticated/dashboard-v3'
      path: '/dashboard-v3'
      fullPath: '/dashboard-v3'
      preLoaderRoute: typeof AuthenticatedDashboardV3RouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard-v2': {
      id: '/_authenticated/dashboard-v2'
      path: '/dashboard-v2'
      fullPath: '/dashboard-v2'
      preLoaderRoute: typeof AuthenticatedDashboardV2RouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contacts-v3': {
      id: '/_authenticated/contacts-v3'
      path: '/contacts-v3'
      fullPath: '/contacts-v3'
      preLoaderRoute: typeof AuthenticatedContactsV3RouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contacts': {
      id: '/_authenticated/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedContactsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/campanhas': {
      id: '/_authenticated/campanhas'
      path: '/campanhas'
      fullPath: '/campanhas'
      preLoaderRoute: typeof AuthenticatedCampanhasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin_/produtos': {
      id: '/_authenticated/admin_/produtos'
      path: '/admin/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AuthenticatedAdminProdutosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin_/convites': {
      id: '/_authenticated/admin_/convites'
      path: '/admin/convites'
      fullPath: '/admin/convites'
      preLoaderRoute: typeof AuthenticatedAdminConvitesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCampanhasRoute: typeof AuthenticatedCampanhasRoute
  AuthenticatedContactsRoute: typeof AuthenticatedContactsRoute
  AuthenticatedContactsV3Route: typeof AuthenticatedContactsV3Route
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDashboardV2Route: typeof AuthenticatedDashboardV2Route
  AuthenticatedDashboardV3Route: typeof AuthenticatedDashboardV3Route
  AuthenticatedDesignSystemRoute: typeof AuthenticatedDesignSystemRoute
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRoute
  AuthenticatedMetasRoute: typeof AuthenticatedMetasRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedRankingRoute: typeof AuthenticatedRankingRoute
  AuthenticatedRankingV2Route: typeof AuthenticatedRankingV2Route
  AuthenticatedRankingV3Route: typeof AuthenticatedRankingV3Route
  AuthenticatedRegistrarProducaoRoute: typeof AuthenticatedRegistrarProducaoRoute
  AuthenticatedRegistrarProducaoV2Route: typeof AuthenticatedRegistrarProducaoV2Route
  AuthenticatedRegistrarProducaoV3Route: typeof AuthenticatedRegistrarProducaoV3Route
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedToolsRoute: typeof AuthenticatedToolsRoute
  AuthenticatedAdminConvitesRoute: typeof AuthenticatedAdminConvitesRoute
  AuthenticatedAdminProdutosRoute: typeof AuthenticatedAdminProdutosRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCampanhasRoute: AuthenticatedCampanhasRoute,
  AuthenticatedContactsRoute: AuthenticatedContactsRoute,
  AuthenticatedContactsV3Route: AuthenticatedContactsV3Route,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDashboardV2Route: AuthenticatedDashboardV2Route,
  AuthenticatedDashboardV3Route: AuthenticatedDashboardV3Route,
  AuthenticatedDesignSystemRoute: AuthenticatedDesignSystemRoute,
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRoute,
  AuthenticatedMetasRoute: AuthenticatedMetasRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedRankingRoute: AuthenticatedRankingRoute,
  AuthenticatedRankingV2Route: AuthenticatedRankingV2Route,
  AuthenticatedRankingV3Route: AuthenticatedRankingV3Route,
  AuthenticatedRegistrarProducaoRoute: AuthenticatedRegistrarProducaoRoute,
  AuthenticatedRegistrarProducaoV2Route: AuthenticatedRegistrarProducaoV2Route,
  AuthenticatedRegistrarProducaoV3Route: AuthenticatedRegistrarProducaoV3Route,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedToolsRoute: AuthenticatedToolsRoute,
  AuthenticatedAdminConvitesRoute: AuthenticatedAdminConvitesRoute,
  AuthenticatedAdminProdutosRoute: AuthenticatedAdminProdutosRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ConviteCodeRoute: ConviteCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
